server:
  port: 7002
spring:
  application:
    name: stream-consumer
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input:
          destination: itcast-default
        myinput:
          destination: itcast-consumer-default
      binders:
        defaultRabbit:
          type: rabbit